services:
  web:
    container_name: geotime-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "preview"]
    environment:
      NODE_ENV: production
    
    
# services:
#   react-app:
#     container_name: geotime-front
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     volumes:
#       - .:/app
#     environment:
#       NODE_ENV: production